import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Image
          className={styles.logo}
          src="/b.jpeg"
          alt="Next.js Logo"
          width={320}
          height={320}
          priority
        />
        <Image
          className={styles.logo}
          src="/m.JPG"
          alt="Next.js Logo"
          width={320}
          height={320}
          priority
        />
        <Image
          className={styles.logo}
          src="/i.jpeg"
          alt="Next.js Logo"
          width={320}
          height={320}
          priority
        />
      </main>
    </>
  )
}
